### ISSUE TITLE
Información del proyecto

### ISSUE THREAD

**Issue by roadev** [Writkas/iKourses#1]
¿La información se encuentra en el drive de rubyespañol?
Para saber detalladamente qué se quiere lograr.

**Comment by Writkas** [comment]
En la carpeta del grupo de rails se encuentra un resumen pequeño, pero tengo más información sobre el proyecto en otras carpetas. Es que es un proyecto que tenía en mente hace tiempo y la idea no se si habrá cambiado mucho o no. Pero si te intereza te comparto la carpeta.

**Comment by Writkas** [comment]
Si se necesita más información sobre el proyecto, se me puede consultar y yo le comparto el borrador temporal de la idea. Si se quiere participar activamente en el proyecto se podría crear una nueva org para eso.
